### PR TITLE
ACE3 Cargo + G41 & FG42 AB Entries

### PR DESCRIPTION
**Pull request by ghost**
Cargo for vehicles:
- Horsa
- Waco
- C47
- Ju 52

Compatibility for boxes:
- All US Boxes
- All 60mm boxes
- All German boxes
- All 81mm boxes

### CODE REVIEW

**Comment by ghost** [comment]
Added compatibility for future Ju 52 and all German boxes including mortar ammo.

**Comment by ghost** [comment]
Added ACE AB entries for LIB_G41 and LIB_FG42G.

**Comment by Drofseh** [comment]
The G41 barrel twist is commented with `//unknown set to same as K98` but does not have same value as the K98.

**Comment by ghost** [comment]
@Drofseh Mistake on my part, should be marked for barrelTwist, not Length. Will fix asap.

**Pull request merged**
